---
- name: configure vsftpd
  hosts: all
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: latest
    - name: start vsftpd
      service:
        name: vsftpd
        state: started
        enabled: true
